# Generated by Django 3.2.19 on 2023-06-09 18:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biop',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=2000, null=True),
        ),
    ]
