# Generated by Django 3.2.19 on 2023-05-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish',
            new_name='approved',
        ),
    ]
