# Generated by Django 3.2.19 on 2023-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_alt',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
