# Generated by Django 3.2.19 on 2023-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20230610_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
