# Generated by Django 3.2.19 on 2023-06-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('dog_name', models.CharField(max_length=20)),
                ('breed', models.CharField(choices=[('Australian Shepard', 'Australian Shepard'), ('Bassett Hound', 'Bassett Hound'), ('Beagle', 'Beagle'), ('Belgian Shepard', 'Belgian Shepard'), ('Bernese', 'Bernese'), ('Bichon Frise', 'Bichon Frise'), ('Boston Terrier', 'Boston Terrier'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Chihuahua', 'Chihuahua'), ('Collie', 'Collie'), ('Corgi', 'Corgi'), ('Dachshund', 'Dachshund'), ('Doberman', 'Doberman'), ('English Mastiff', 'English Mastiff'), ('Fox Hound', 'Foxhound'), ('Greyhound', 'Greyhound'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Husky', 'Husky'), ('Labrador Retriever', 'Labrador Retriever'), ('Lurcher', 'Lurcher'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Saint Bernard', 'Saint Bernard'), ('Shih Tzu', 'Shih Tzu'), ('Spaniel', 'Spaniel'), ('Terrier', 'Terrier'), ('Weimaraner', 'Weimaraner'), ('Other', 'Other')], max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
