# Generated by Django 3.2.19 on 2023-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='breed2',
            field=models.CharField(blank=True, choices=[('Australian Shepard', 'Australian Shepard'), ('Bassett Hound', 'Bassett Hound'), ('Beagle', 'Beagle'), ('Belgian Shepard', 'Belgian Shepard'), ('Bernese', 'Bernese'), ('Bichon Frise', 'Bichon Frise'), ('Boston Terrier', 'Boston Terrier'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Chihuahua', 'Chihuahua'), ('Collie', 'Collie'), ('Corgi', 'Corgi'), ('Dachshund', 'Dachshund'), ('Doberman', 'Doberman'), ('English Mastiff', 'English Mastiff'), ('Fox Hound', 'Foxhound'), ('Greyhound', 'Greyhound'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Husky', 'Husky'), ('Labrador Retriever', 'Labrador Retriever'), ('Lurcher', 'Lurcher'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Saint Bernard', 'Saint Bernard'), ('Shih Tzu', 'Shih Tzu'), ('Spaniel', 'Spaniel'), ('Terrier', 'Terrier'), ('Weimaraner', 'Weimaraner'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='color2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dog_name2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender2',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_vaccinated2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
